package org.clueminer.wellmap;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
//import org.clueminer.clustering.api.Clustering;
//import org.clueminer.clustering.gui.ClusterAnalysis;
import org.clueminer.dataset.api.Dataset;
import org.clueminer.hts.api.HtsPlate;
import org.clueminer.project.api.Project;
import org.clueminer.project.api.ProjectController;
import org.clueminer.project.api.Workspace;
import org.clueminer.project.api.WorkspaceListener;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;
import org.openide.util.Utilities;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.clueminer.wellmap//WellMap//EN",
autostore = false)
@TopComponent.Description(preferredID = "WellMapTopComponent",
iconBase = "org/clueminer/wellmap/well16.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "org.clueminer.wellmap.WellMapTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_WellMapAction",
preferredID = "WellMapTopComponent")
@Messages({
    "CTL_WellMapAction=WellMap",
    "CTL_WellMapTopComponent=Well Map",
    "HINT_WellMapTopComponent=Well Map displays plate's layout"
})
public final class WellMapTopComponent extends TopComponent implements LookupListener {

    private static final long serialVersionUID = -818362881805020235L;
    private final InstanceContent content = new InstanceContent();
    private Lookup.Result<HtsPlate> result = null;
    //private Lookup.Result<SampleDataset> selection = null;
    private WellMapFrame wellMap;
    //private ClusterAnalysis clust;
    protected static Project project;
    private WorkspaceListener workspaceListener;

    public WellMapTopComponent() {
        //Add the dynamic object to the TopComponent Lookup:
        associateLookup(new AbstractLookup(content));
        initComponents();
        setName(Bundle.CTL_WellMapTopComponent());
        setToolTipText(Bundle.HINT_WellMapTopComponent());
        setBackground(Color.LIGHT_GRAY);
        //component is responsible for all pixels within the component
        setOpaque(true);
        wellMap = new WellMapFrame();
        add(wellMap, new GridBagConstraints(0, 0, 1, 1, 1.0, 1.0, GridBagConstraints.NORTHWEST, GridBagConstraints.BOTH, new Insets(0, 0, 0, 0), 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
        pc.addWorkspaceListener(new WorkspaceListener() {
            @Override
            public void initialize(Workspace workspace) {
                Logger.getLogger(this.getClass().getName()).log(Level.INFO, "wellmap listener initialized");
            }

            @Override
            public void select(Workspace workspace) {
                System.out.println("workspace: " + workspace.toString());
                Logger.getLogger(this.getClass().getName()).log(Level.INFO, "wellmap selected");
                System.out.println("workspace selected: got result (plate)");
                result = workspace.getLookup().lookupResult(HtsPlate.class);
                System.out.println("lookup res= " + result.toString());

                HtsPlate plt = workspace.getLookup().lookup(HtsPlate.class);
                System.out.println("got plate, size: " + plt);
                //  result.addLookupListener(parent);
            }

            @Override
            public void unselect(Workspace workspace) {
                if (result != null) {
                    //   result.removeLookupListener(parent);
                }
            }

            @Override
            public void close(Workspace workspace) {
            }

            @Override
            public void disable() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void projectActivated(Project proj) {
                project = proj;
                projectChanged();
            }
        });


       /* selection = Utilities.actionsGlobalContext().lookupResult(SampleDataset.class);

        selection.addLookupListener(this);
        resultChanged(new LookupEvent(selection));*/
    }

    @Override
    public void componentClosed() {
        ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
        pc.removeWorkspaceListener(workspaceListener);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    /*
     @Override
     public void projectOpened(ProjectEvent evt) {
     System.out.println("well map: project opened");
     wellMap.setPlate((Plate) ((IProjectFrame) evt.getSource()).getDataset());
     System.out.println("looking up for DendrogramViewer class");
     clust = Lookup.getDefault().lookup(DendrogramComponent.class);
     if (clust != null) {
     clust.addRowsTreeListener(wellMap);
     System.out.println("registrered listener to " + clust.getName());
     }
     repaint();
     }
     */
    @Override
    public void resultChanged(LookupEvent ev) {
        System.out.println("well map result " + ev.toString());
        if (result != null) {
            Collection<? extends HtsPlate> allPlatex = result.allInstances();
            for (HtsPlate p : allPlatex) {
                System.out.println("got plate " + p.getName());
                wellMap.setPlate(p);
            }
        }

      /*  if (selection != null) {
            System.out.println("selection " + selection.toString());
        }*/
    }

    protected void projectChanged() {
        HtsPlate plt = project.getLookup().lookup(HtsPlate.class);
        wellMap.setPlate(plt);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                wellMap.update();
                setVisible(true);
            }
        });

    }
}
