package org.clueminer.xcalibour.plot3d;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.RepaintManager;
import org.clueminer.xcalibour.data.MassSpectrum;
import org.clueminer.xcalibour.data.SpectrumDataset;
import org.clueminer.xcalibour.files.MyOrthoGrid;
import org.clueminer.xcalibour.files.SpectrumMapper;
import org.jzy3d.chart.Chart;
import org.jzy3d.chart.controllers.mouse.camera.NewtCameraMouseController;
import org.jzy3d.chart.controllers.thread.camera.CameraThreadController;
import org.jzy3d.colors.Color;
import org.jzy3d.colors.ColorMapper;
import org.jzy3d.colors.colormaps.ColorMapRainbow;
import org.jzy3d.maths.Coord3d;
import org.jzy3d.maths.Range;
import org.jzy3d.plot3d.builder.Builder;
import org.jzy3d.plot3d.primitives.Shape;
import org.jzy3d.plot3d.rendering.canvas.Quality;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.clueminer.xcalibour.plot3d//XCalibour3d//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "XCalibour3dTopComponent",
        iconBase = "org/clueminer/xcalibour/3d-16b.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.clueminer.xcalibour.plot3d.XCalibour3dTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_XCalibour3dAction",
        preferredID = "XCalibour3dTopComponent")
@Messages({
    "CTL_XCalibour3dAction=XCalibour3d",
    "CTL_XCalibour3dTopComponent=XCalibour3d Window",
    "HINT_XCalibour3dTopComponent=This is a XCalibour3d window"
})
public final class XCalibour3dTopComponent extends TopComponent {

    private static final long serialVersionUID = -6373865320338304931L;
    private Chart chart;
    private Component canvas;
    private Shape surface;
    private CameraThreadController ctc;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private SpectrumDataset<MassSpectrum> dataset;

    public XCalibour3dTopComponent() {
        setOpaque(true);
        initComponents();
        createComponets();
        setName(Bundle.CTL_XCalibour3dTopComponent());
        setToolTipText(Bundle.HINT_XCalibour3dTopComponent());

    }

    private void createComponets() {
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        org.openide.awt.Mnemonics.setLocalizedText(jToggleButton1, org.openide.util.NbBundle.getMessage(XCalibour3dTopComponent.class, "XCalibour3dTopComponent.jToggleButton1.text")); // NOI18N
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    protected void componentOpened() {
        super.componentOpened();
        System.out.println("Opened");
        createChart();
    }

    @Override
    protected void componentClosed() {
        super.componentClosed();
        System.out.println("Closed");
        if (chart != null) {
            try {
                chart.dispose();
                chart = null;
                canvas = null;
                surface = null;
                ctc = null;
            } catch (Exception e) {
                Exceptions.printStackTrace(e);
            }
        }
    }

    @Override
    protected void componentShowing() {
        super.componentShowing();
        System.out.println("Showing");
    }

    @Override
    protected void componentHidden() {
        super.componentHidden();
        System.out.println("Hidden");
    }

    @Override
    protected void componentActivated() {
        super.componentActivated();
        System.out.println("Activated");
        RepaintManager.currentManager(this).addInvalidComponent(this);
    }

    @Override
    protected void componentDeactivated() {
        super.componentDeactivated();
        System.out.println("Deactivated");
        RepaintManager.currentManager(this).addInvalidComponent(this);
    }

    private void createChart() {
        if (chart == null && dataset != null) {
            chart = new Chart(Quality.Advanced, "newt");
            chart.getView().setMaximized(true);
            canvas = (Component) chart.getCanvas();
            ctc = new CameraThreadController(chart);
            ctc.start();
            jToggleButton1.setSelected(true);
            NewtCameraMouseController camMouse = new NewtCameraMouseController(chart);
            chart.addController(camMouse);
            add(canvas, BorderLayout.CENTER);

            SpectrumMapper mapper = new SpectrumMapper();
            mapper.setDataset(dataset);

// Define range and precision for the function to plot
            Range xrange = new Range(0, dataset.attributeCount() - 1);
            int xsteps = 2500;

            Range yrange = new Range(30, 200);
            int ysteps = 170;

// Create a surface drawing that function
            MyOrthoGrid grid = new MyOrthoGrid(xrange, xsteps, yrange, ysteps);
            //OrthonormalGrid grid = new OrthonormalGrid(xrange, xsteps, yrange, ysteps);
            surface = Builder.buildOrthonormal(grid, mapper);
            surface.setColorMapper(new ColorMapper(new ColorMapRainbow(), surface.getBounds().getZmin(), surface.getBounds().getZmax(), new Color(1, 1, 1, .5f)));
            surface.setFaceDisplayed(true);
            surface.setWireframeDisplayed(false);
            surface.setWireframeColor(Color.BLACK); // set polygon border in black
            //surface.setFace(new FaceColorbar(surface)); // attach a 2d panel
            //surface.setFace2dDisplayed(true);         

            //chart.setViewPoint( Coord3d.ORIGIN);
            chart.setViewPoint(new Coord3d(0.5f, 0.5f, 0.5f));
            //ChartLauncher.openChart(chart);
            surface.setFaceDisplayed(true);
            surface.setWireframeDisplayed(false);
            surface.setWireframeColor(Color.BLACK);
            chart.getScene().getGraph().add(surface, true);
        }
    }

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (ctc != null) {
            if (jToggleButton1.isSelected()) {
                ctc.start();
            } else {
                ctc.stop();
            }
        }
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    public SpectrumDataset<MassSpectrum> getDataset() {
        return dataset;
    }

    public void setDataset(SpectrumDataset<MassSpectrum> dataset) {
        this.dataset = dataset;
    }
}
