/*
 * Copyright (C) 2011-2018 clueminer.org
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.clueminer.visualize;

import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.Collection;
import org.clueminer.clustering.api.Clustering;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Cluster visualization
 */
@ConvertAsProperties(
        dtd = "-//org.clueminer.visualize//VisualizeCluster//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "VisualizeClusterTopComponent",
        iconBase = "org/clueminer/visualize/visualize-cluster.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "org.clueminer.visualize.VisualizeClusterTopComponent")
@ActionReference(path = "Menu/Window", position = 120)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_VisualizeClusterAction",
        preferredID = "VisualizeClusterTopComponent"
)
@Messages({
    "CTL_VisualizeClusterAction=Cluster visualization",
    "CTL_VisualizeClusterTopComponent=Cluster visualization",
    "HINT_VisualizeClusterTopComponent=Displays objects assigned to clusters"
})
public final class VisualizeClusterTopComponent extends TopComponent implements LookupListener, Lookup.Provider {

    private final InstanceContent content = new InstanceContent();
    private Lookup.Result<Clustering> result = null;
    private VisualizePanel frame;
    private VisualizeToolbar toolbar;
    private static final Logger LOG = LoggerFactory.getLogger(VisualizeClusterTopComponent.class);

    public VisualizeClusterTopComponent() {
        initComponents();
        associateLookup(new AbstractLookup(content));
        setName(Bundle.CTL_VisualizeClusterTopComponent());
        setToolTipText(Bundle.HINT_VisualizeClusterTopComponent());
        initialize();
    }

    private void initialize() {
        frame = new VisualizePanel();
        GridBagConstraints c = new GridBagConstraints();
        c.anchor = GridBagConstraints.NORTHWEST;
        c.fill = GridBagConstraints.BOTH;
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 1;
        c.gridheight = 1;
        c.weightx = 1.0;
        c.weighty = 1.0;
        c.insets = new Insets(0, 0, 0, 0);
        add((Component) frame, c);
        toolbar = new VisualizeToolbar(frame);
        c.gridy = 0;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.weighty = 0;
        add(toolbar, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        result = Utilities.actionsGlobalContext().lookupResult(Clustering.class);
        result.addLookupListener(this);
        resultChanged(new LookupEvent(result));
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
        result = null;
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void resultChanged(LookupEvent le) {
        Collection<? extends Clustering> allClusterings = result.allInstances();
        if (allClusterings.size() > 0) {
            LOG.trace("visualize cluster: got {} clusterings", allClusterings.size());
            for (Clustering c : allClusterings) {
                frame.setClustering(c);
            }
        }
    }
}
