package org.clueminer.export.newick;

import java.util.prefs.Preferences;

/**
 *
 * @author deric
 */
public class NewickOptions extends javax.swing.JPanel {

    public static final String INNER_NODES_NAMES = "inner_nodes_names";

    /**
     * Creates new form NewickOptions
     */
    public NewickOptions() {
        initComponents();
    }

    public Preferences updatePreferences(Preferences p) {
        boolean includeInnerNodes = false;
        if (chckInnerNodes.isSelected()) {
            includeInnerNodes = true;
        }
        p.putBoolean(INNER_NODES_NAMES, includeInnerNodes);

        return p;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chckInnerNodes = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(chckInnerNodes, org.openide.util.NbBundle.getMessage(NewickOptions.class, "NewickOptions.chckInnerNodes.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chckInnerNodes)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chckInnerNodes)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chckInnerNodes;
    // End of variables declaration//GEN-END:variables
}
