package org.clueminer.explorer.gui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.clueminer.clustering.api.ClusterEvaluation;
import org.clueminer.clustering.api.factory.ExternalEvaluatorFactory;
import org.clueminer.clustering.api.factory.InternalEvaluatorFactory;

/**
 *
 * @author deric
 */
public class EvolutionPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -8908500509479257849L;

    /**
     * Creates new form EvolutionPanel
     */
    public EvolutionPanel() {
        initComponents();
    }

    private String[] initExternal() {
        ExternalEvaluatorFactory ef = ExternalEvaluatorFactory.getInstance();
        List<String> list = ef.getProviders();
        return list.toArray(new String[list.size()]);
    }

    public ClusterEvaluation getEvaluator() {
        String eval;
        ClusterEvaluation evaluator;
        if (rbExternal.isSelected()) {
            eval = (String) cbExtern.getSelectedItem();
            evaluator = ExternalEvaluatorFactory.getInstance().getProvider(eval);
        } else {
            eval = (String) cbIntern.getSelectedItem();
            evaluator = InternalEvaluatorFactory.getInstance().getProvider(eval);
        }

        return evaluator;
    }

    private String[] initInternalEvaluator() {
        InternalEvaluatorFactory ef = InternalEvaluatorFactory.getInstance();
        List<String> list = ef.getProviders();
        return list.toArray(new String[list.size()]);
    }

    public int getGenerations() {
        return sliderGen.getValue();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evalGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        sliderGen = new javax.swing.JSlider();
        lbGen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sliderPop = new javax.swing.JSlider();
        lbPop = new javax.swing.JLabel();
        rbInternal = new javax.swing.JRadioButton();
        rbExternal = new javax.swing.JRadioButton();
        cbIntern = new javax.swing.JComboBox();
        cbExtern = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EvolutionPanel.class, "EvolutionPanel.jLabel1.text")); // NOI18N

        sliderGen.setMaximum(1000);
        sliderGen.setMinimum(1);
        sliderGen.setValue(10);

        org.openide.awt.Mnemonics.setLocalizedText(lbGen, org.openide.util.NbBundle.getMessage(EvolutionPanel.class, "EvolutionPanel.lbGen.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EvolutionPanel.class, "EvolutionPanel.jLabel2.text")); // NOI18N

        sliderPop.setMaximum(1000);
        sliderPop.setMinimum(10);
        sliderPop.setValue(20);

        org.openide.awt.Mnemonics.setLocalizedText(lbPop, org.openide.util.NbBundle.getMessage(EvolutionPanel.class, "EvolutionPanel.lbPop.text")); // NOI18N

        evalGroup.add(rbInternal);
        org.openide.awt.Mnemonics.setLocalizedText(rbInternal, org.openide.util.NbBundle.getMessage(EvolutionPanel.class, "EvolutionPanel.rbInternal.text")); // NOI18N

        evalGroup.add(rbExternal);
        org.openide.awt.Mnemonics.setLocalizedText(rbExternal, org.openide.util.NbBundle.getMessage(EvolutionPanel.class, "EvolutionPanel.rbExternal.text")); // NOI18N

        cbIntern.setModel(new DefaultComboBoxModel(initInternalEvaluator()));

        cbExtern.setModel(new DefaultComboBoxModel(initExternal()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbExternal)
                            .addComponent(rbInternal)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPop))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(sliderGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbGen))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cbIntern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cbExtern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbGen)
                    .addComponent(sliderGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(sliderPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPop))
                .addGap(18, 18, 18)
                .addComponent(rbInternal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbIntern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(rbExternal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbExtern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbExtern;
    private javax.swing.JComboBox cbIntern;
    private javax.swing.ButtonGroup evalGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbGen;
    private javax.swing.JLabel lbPop;
    private javax.swing.JRadioButton rbExternal;
    private javax.swing.JRadioButton rbInternal;
    private javax.swing.JSlider sliderGen;
    private javax.swing.JSlider sliderPop;
    // End of variables declaration//GEN-END:variables
}
