package org.clueminer.meta.view;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.Collection;
import javax.swing.SwingUtilities;
import org.clueminer.dataset.api.Dataset;
import org.clueminer.dataset.api.Instance;
import org.clueminer.meta.api.MetaStorageFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.clueminer.meta.view//MetaViewer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "MetaViewerTopComponent",
        iconBase = "org/clueminer/meta/view/meta16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = true)
@ActionID(category = "Window", id = "org.clueminer.meta.view.MetaViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_MetaViewerAction",
        preferredID = "MetaViewerTopComponent"
)
@Messages({
    "CTL_MetaViewerAction=MetaViewer",
    "CTL_MetaViewerTopComponent=MetaViewer Window",
    "HINT_MetaViewerTopComponent=This is a MetaViewer window"
})
public final class MetaViewerTopComponent extends TopComponent implements LookupListener {

    private static final long serialVersionUID = -950662751709594103L;
    private final MetaPanel panel;
    private Lookup.Result<Dataset> result = null;

    public MetaViewerTopComponent() {
        initComponents();
        setName(Bundle.CTL_MetaViewerTopComponent());
        setToolTipText(Bundle.HINT_MetaViewerTopComponent());
        panel = new MetaPanel();
        add(panel, new GridBagConstraints(0, 0, 1, 1, 1.0, 1.0, GridBagConstraints.NORTHWEST, GridBagConstraints.BOTH, new Insets(0, 0, 0, 0), 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        result = Utilities.actionsGlobalContext().lookupResult(Dataset.class);
        result.addLookupListener(this);

        MetaStorageFactory mf = MetaStorageFactory.getInstance();
        panel.setStorage(mf.getDefault());
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void resultChanged(LookupEvent ev) {

        if (result != null) {
            Collection<? extends Dataset> allDatasets = result.allInstances();
            for (final Dataset<? extends Instance> d : allDatasets) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        panel.updateDataset(d);
                    }
                });
            }
        }
    }
}
