package org.clueminer.clustering.confusion;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.clueminer.clustering.confusion//Confusion//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ConfusionTopComponent",
        iconBase = "org/clueminer/clustering/confusion/conf16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "org.clueminer.clustering.confusion.ConfusionTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ConfusionAction",
        preferredID = "ConfusionTopComponent"
)
@Messages({
    "CTL_ConfusionAction=Confusion",
    "CTL_ConfusionTopComponent=Confusion Window",
    "HINT_ConfusionTopComponent=This is a Confusion window"
})
public final class ConfusionTopComponent extends TopComponent {

    private static final long serialVersionUID = -812734476374687722L;

    private final ConfusionMatrix matrix;

    public ConfusionTopComponent() {
        initComponents();
        setName(Bundle.CTL_ConfusionTopComponent());
        setToolTipText(Bundle.HINT_ConfusionTopComponent());
        matrix = new ConfusionMatrix();
        add(matrix, new GridBagConstraints(0, 0, 1, 1, 1.0, 1.0, GridBagConstraints.NORTHWEST, GridBagConstraints.BOTH, new Insets(0, 0, 0, 0), 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
